import sys

sys.path.append(".")
from ibis.core.trading_constants import TRADING
from ibis.core.config import Config

print("=== TRADING CONSTANTS ===")
print(f"MIN_CAPITAL_PER_TRADE: ${TRADING.POSITION.MIN_CAPITAL_PER_TRADE}")
print(f"MAX_CAPITAL_PER_TRADE: ${TRADING.POSITION.MAX_CAPITAL_PER_TRADE}")
print(f"MAX_POSITION_PCT: {TRADING.POSITION.MAX_POSITION_PCT}%")
print(f"BASE_POSITION_PCT: {TRADING.POSITION.BASE_POSITION_PCT}%")
print(f"MAX_TOTAL_POSITIONS: {TRADING.POSITION.MAX_TOTAL_POSITIONS}")
print(f"MAX_PORTFOLIO_RISK: {TRADING.RISK.MAX_PORTFOLIO_RISK * 100}%")
print(f"PORTFOLIO_HEAT: {TRADING.RISK.PORTFOLIO_HEAT * 100}%")
print(f"MIN_VIABLE_TARGET: {TRADING.INTELLIGENCE.MIN_VIABLE_TARGET * 100}%")
print()
print("=== CONFIG.PY ===")
print(f"MIN_CAPITAL_PER_TRADE: ${Config.MIN_CAPITAL_PER_TRADE}")
print(f"MAX_CAPITAL_PER_TRADE: ${Config.MAX_CAPITAL_PER_TRADE}")
print(f"MAX_POSITIONS: {Config.MAX_POSITIONS}")
print(f"MIN_VIABLE_TARGET: {Config.MIN_VIABLE_TARGET * 100}%")
